name: 'Cucumber to Azure DevOps Test Plans Sync'
author: 'PavanMudigonda'
description: 'A GitHub Action that Synchronizes Cucumber Test Cases and Test Results from GitHub to Azure DevOps'

branding:
  icon: 'repeat'
  color: 'red'

inputs:
  github_token:
    description: 'GitHub API Access Token'
    default: ${{ github.token }}
    required: false
  test_cases_sync:  
    description: 'Test Cases Sync'
    required: true
    default: 'false'
  test_results_sync:
    description: 'Test Results Sync - Format Supported'
    required: false
    default: 'false'
  ado_pat:
    description: 'Azure DevOps PAT'
    required: true
  ado_project_url:
    description: 'ADO Project URL'
    required: true
  ado_area_path:
    description: 'ADO Area Path. Example: \\Release 1'
    required: true
  ado_iteration_path:
    description: 'ADO Iteration or Sprint Path. Example: \\Sprint 1'
    required: true
  cucumber_path:
    description: 'Path of Cucumber Features'
    required: true
  cucumber_language:
    description: 'Default Language of Cucumber Features'
    required: false
    default: 'en-US'
  test_case_tag_prefix:
    description: 'Test Case Tag Prefix'
    required: false
    default: 'ADO'
  test_suite_id:
    description: 'ID of Test Suite. Only if you have not specified test_suite_name'
    required: true
  test_suite_name:
    description: 'Name of Test Suite. Only if you have not specified test_suite_id'
    required: true    
  default_test_case_status:
    description: 'Default test case status. Defaults to Design'
    required: false
    default: 'Design'
  git_user_email:
    description: 'Default Github Actions Email'
    required: false
    default: 'actions@github.com'
  git_user_name:
    description: 'Default Github Actions Name'
    required: false
    default: 'GitHub Actions'
  cucumber_branch_name:
    description: 'Default Github Actions Name'
    required: false
    default: 'cucumber-ado-sync'
  temp_cucumber_branch_name:
    description: 'Default Github Actions Name'
    required: false
    default: 'temp-cucumber-ado-sync'
  test_configuration_name:
    description: 'Test Result - Configuration Run name'
    required: false
    default: ${{ runner.os }}-${{ runner.arch }}
  test_configuration_id:
    description: 'Test Result - Configuration Run ID'
    required: false
  test_results_file_path:
    description: 'Test Result - File Path'
    required: false
  test_results_file_format:
    description: 'Test Result - File Format'
    required: false    
  test_results_run_comment:
    description: 'Test Result - Run Comment'
    required: false
    default: GH Action-${{ github.run_id}}
  test_results_run_name:
    description: 'Test Result - Run NAme'
    required: false
    default: GH-Actions-${{ github.run_id }}
  test_results_run_type:
    description: 'Test Result - Run Type'
    required: false
    default: 'automated'
  test_results_run_result_comment:
    description: 'Test Result - Run Result Comment'
    required: false
    default: 'As Expected'
  test_results_test_suite_name:
    description: 'Test Result - Test Suite Name'
    required: false
  test_results_test_suite_id:
    description: 'Test Result - Test Suite ID'
    required: false
    default: ${{ inputs.test_suite_id }}
  test_results_test_plan_id:
    description: 'Test Result - Test Plan ID'
    required: false
  test_results_create_sub_results:
    description: 'Test Result - Create Sub Results'
    required: false
    default: 'false'
  test_results_treat_inconclusive_as:
    description: 'Test Result - Treat Inconclusive As'
    required: false
    default: 'NotExecuted'

runs:
  using: 'composite'
  steps:
      - name: Check If there is a change in Feature Files from last commit/trigger branch
        uses: dorny/paths-filter@v2
        if: ${{ inputs.test_cases_sync }}    
        id: pre-ado-sync
        with:
          base: ${{ env.GITHUB_SHA }}
          filters: |
            features:
             - '${{ inputs.cucumber_path }}/**'

      - name: Check If there is a change in Test Results Path in local
        uses: dorny/paths-filter@v2
        if: ${{ inputs.test_results_sync }} 
        id: post-test-execution
        with:
          base: ${{ env.GITHUB_SHA }}
          filters: |
            test_results_file_path:
             - '${{ inputs.test_results_file_path }}/**'

      - name: Create SpecSync.json file
        if: ${{ ( inputs.test_cases_sync || inputs.test_results_sync ) && (steps.pre-ado-sync.outputs.features || steps.post-test-execution.outputs.test_results_file_path ) && always() }}
        shell: bash
        run: |
          cat > ./specsync.json <<EOF
          {
            "$schema": "https://schemas.specsolutions.eu/specsync4azuredevops-config-latest.json",
            "compatibilityVersion": "3.3",
            "toolSettings": {
              "licensePath": "specsync.lic",
              "disableStats": true,
              "outputLevel": "normal"
            },   
            "remote": {
              "projectUrl": "https://dev.azure.com/tr-ihn-sandbox/Azure%20DevOps%20Training",
              "user":"ADO_PAT",
              "testSuite": {
                      "name": "TEST_SUITE_NAME",
                      "id": 1
                    }
            },
            "local": {
                  "featureFileSource": {
                    "type": "folder",
                    "folder": "features"
                  },
                  "defaultFeatureLanguage":"en-US"
                },
                "publishTestResults": {
                  "testConfiguration": {
                        "name": "Windows 10"
                   },
                   "testResult": {
                   "filePath": "test-result.trx"
                    },
                    "runComment": "Acceptance test results",
                    "treatInconclusiveAs":"NotExecuted",
                    "createSubResults": true,
                    "runName": "test",
                    "runType": "automated",
                    "runComment": "test",
                    "testResultComment": "test",
                    "testSuite": {
                      "name": "test",
                      "id": 2,
                      "testPlanId": "1"
                       }
                     },
                "synchronization": {
                  "disableLocalChanges": false,
                  "testCaseTagPrefix": "ADO",
              
                  "pull": {
                    "enabled": true,
                    "enableCreatingScenariosForNewTestCases": true
                  },
              
                  "automation": {
                    "enabled": true,
                    "condition": "not @manual"
                  },
              
                  "state": {
                    "setValueOnChangeTo": "Design"
                  },
              
                  "areaPath": {
                    "mode": "setOnLink",
                    "value": "MyArea"
                  },
                  "iterationPath": {
                    "mode": "setOnLink",
                    "value": "Sprint 1"
                  },
                  "links": [
                    {
                      "targetWorkItemType": "ProductBacklogItem",
                      "tagPrefix": "story",
                      "relationship": "Child",
                      "mode": "createIfMissing"
                    },
                    {
                      "tagPrefix": "bug"
                    }
                  ],
                  "format": {
                    "useExpectedResult": false,
                    "syncDataTableAsText": false,
                    "prefixBackgroundSteps": true,
                    "prefixTitle": true,
                    "showParameterListStep": "whenUnusedParameters"
                  }
                },
                "customizations": {
                    "ignoreTestCaseSteps": {
                      "enabled": true,
                      "ignoredPrefixes": [ "COMMENT" ]
                    },
                    "ignoreTestCaseTags": {
                      "enabled": true,
                      "tags": [ "ignore" ]
                    },  
                    "resetTestCaseState": {
                      "enabled": true,
                      "state": "Ready",
                      "condition": "@ready"
                    }
                  }                          
          }
          EOF

      - uses: microsoft/variable-substitution@v1
        if: ${{ ( inputs.test_cases_sync || inputs.test_results_sync ) && (steps.pre-ado-sync.outputs.features || steps.post-test-execution.outputs.test_results_file_path ) && always() }}
        with:
          files: './specsync.json'
        env:
          remote.projectUrl: ${{ inputs.ado_project_url }}
          remote.user: ${{ inputs.ado_pat }}
          remote.testSuite.name: ${{ inputs.test_suite_name }}
          remote.testSuite.id: ${{ inputs.test_suite_id }}
          local.featureFileSource.folder: ${{ inputs.cucumber_path }}
          local.defaultFeatureLanguage: ${{ inputs.cucumber_language }}
          synchronization.testCaseTagPrefix: ${{ inputs.test_case_tag_prefix }}
          synchronization.state.setValueOnChangeTo: ${{ inputs.default_test_case_status }}
          synchronization.areaPath.value: ${{ inputs.ado_area_path }}
          synchronization.iterationPath.value: ${{ inputs.ado_iteration_path }}
          publishTestResults.testConfiguration.name: ${{ inputs.test_configuration_name }}
          publishTestResults.testConfiguration.id: ${{ inputs.test_configuration_id }}
          publishTestResults.testResult.filePath: ${{ inputs.test_results_file_path }}
          publishTestResults.testResult.fileFormat: ${{ inputs.test_results_file_format }}
          publishTestResults.runComment: ${{ inputs.test_results_run_comment }}
          publishTestResults.runName: ${{ inputs.test_results_run_name }}
          publishTestResults.runType: ${{ inputs.test_results_run_type }}
          publishTestResults.testResultComment: ${{ inputs.test_results_run_result_comment }}
          publishTestResults.testSuite.name: ${{ inputs.test_results_test_suite_name }}
          publishTestResults.testSuite.id: ${{ inputs.test_results_test_suite_id }}
          publishTestResults.testSuite.testPlanId: ${{ inputs.test_results_test_plan_id }}          
          publishTestResults.createSubResults: ${{ inputs.test_results_create_sub_results }}

      - name: retain either name of id variable in specsync json file based on user input
        if: ${{ ( inputs.test_cases_sync || inputs.test_results_sync ) && (steps.pre-ado-sync.outputs.features || steps.post-test-execution.outputs.test_results_file_path ) && always() }}
        shell: bash
        run: |
          if [[ '${inputs.test_suite_name}' != '' ]];
          then
            sed '/"id": 1/d' ./specsync.json;
          elif [[ '${inputs.test_suite_id}' != '' ]];
          then
            sed '/"name": "TEST_SUITE_NAME",/d' ./specsync.json;
          elif [[ '${inputs.test_results_sync }' == 'true' ]];
          then
            sed '/"name": "TEST_SUITE_NAME",/d' ./specsync.json;
          else
            echo "either enter test_suite_name or test_suite_id";
          fi
          
          if [[ '${inputs.test_results_sync}' == 'true' && '${inputs.test_results_test_suite_name}' != '' ]];
          then
            sed '/"id": 2,/d' ./specsync.json;
          elif [[ '${inputs.test_results_sync}' == 'true' && '${inputs.test_results_test_suite_id}' != '' ]];
          then
            sed '/"name": "test",/d' ./specsync.json;
          else
            sed '/"name": "test",/d' ./specsync.json;
          fi
      - name: Create SpecSync License file
        if: ${{ ( inputs.test_cases_sync || inputs.test_results_sync ) && (steps.pre-ado-sync.outputs.features || steps.post-test-execution.outputs.test_results_file_path ) && always() }}
        shell: bash
        run: |
          cat > ./specsync.lic <<EOF
          3de10d45-d3cc-9dd7-3ac4-16dff5177c63
          KATzuYGGEkUXKioMDYfSoDPMMqD/M0gyHVRGALVypsFRBebO5BscQfgBFcH0BzMgdGVhbXM=
          Thomson Reuters-West Publishing Corp. (coordinator: Lada Korine)
          3 teams
          Enterprise
          2023-06-25
          EOF

      - name: Set up .NET 6
        if: ${{ ( inputs.test_cases_sync || inputs.test_results_sync ) && (steps.pre-ado-sync.outputs.features || steps.post-test-execution.outputs.test_results_file_path ) && always() }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.0.x"

      - name: Install Dependencies
        if: ${{ ( inputs.test_cases_sync || inputs.test_results_sync ) && (steps.pre-ado-sync.outputs.features || steps.post-test-execution.outputs.test_results_file_path ) && always() }}
        shell: bash
        run: |
          sudo apt install zip unzip
          export PATH="$PATH:/root/.dotnet/tools";
          wget -O SpecSync.zip https://www.specsolutions.eu/media/specsync/SpecSync.AzureDevOps.3.3.6-linux-x64.zip && unzip SpecSync.zip;
          chmod +x SpecSync4AzureDevOps;
                    
      - name: Run Test Case Synchronization
        if: ${{ steps.pre-ado-sync.outputs.features && inputs.test_cases_sync && always() }}
        shell: bash
        run: |
          chmod +x ./SpecSync4AzureDevOps;
          ./SpecSync4AzureDevOps push ./specsync.json
          ./SpecSync4AzureDevOps pull ./specsync.json

      - name: Run Test Results Synchronization
        if: ${{ inputs.test_results_sync && steps.post-test-execution.outputs.test_results_file_path && always() }}
        shell: bash
        run: |
          export RUN_ID=${{ github.run_id }};
          export RUN_ID="echo $((RUN_ID))";
          cd ${{ github.workspace }}
          ls -R;
          chmod +x ./SpecSync4AzureDevOps;
          chmod +x ${{ inputs.test_results_file_path }};
          ./SpecSync4AzureDevOps publish-test-results --zeroExitCodeForWarnings ./specsync.json;
          
      - uses: dorny/paths-filter@v2
        if: ${{ steps.pre-ado-sync.outputs.features && inputs.test_cases_sync && always()  }}
        id: post-ado-sync
        with:
          base: ${{ github.ref }}
          filters: |
            features:
             - '${{ inputs.cucumber_path }}/**'

      #  Commit Cucumber Feature Files to triggering branch or cucumber-ado-sync branch
      - name: Commit updates feature files
        if: ${{ steps.post-ado-sync.outputs.features && inputs.test_cases_sync }}
        shell: bash
        env:
          GITHUB_REF_NAME: ${{ env.GITHUB_REF_NAME }}
          GIT_USER_EMAIL: ${{ inputs.git_user_email }}
          GIT_USER_NAME: ${{ inputs.git_user_name }}
          cucumber_path: ${{ inputs.cucumber_path }}
          CUCUMBER_BRANCH_NAME: ${{ inputs.cucumber_branch_name }}
          TEMP_CUCUMBER_BRANCH_NAME: ${{ inputs.temp_cucumber_branch_name }}
        run: |
          git config --local user.email $GIT_USER_EMAIL
          git config --local user.name $GIT_USER_NAME
          if [ $GITHUB_REF_NAME != "main" ]
          then
            git pull --ff -q
            git add ${{ env.cucumber_path }}
            git commit -m 'Updated Cucumber Gherkins Features'
            git push
          fi
          git add ${{ env.cucumber_path }}/
          if [ `git branch -r --list "origin/${{ env.CUCUMBER_BRANCH_NAME }}"` ]
          then
              git checkout -b ${{ env.TEMP_CUCUMBER_BRANCH_NAME }}
              git commit -m "Updated cucumber branch"
              if [ $GITHUB_REF_NAME == "main" ]
              then
                git stash
              fi
              git checkout ${{ env.CUCUMBER_BRANCH_NAME }}
              git checkout ${{ env.TEMP_BADGE_BRANCH_NAME }} ${{ env.cucumber_path }}
              git add ${{ env.cucumber_path }}/
              git commit -m "Updated Cucumber Feature Files"
              git push --force
              git branch -D ${{ env.TEMP_CUCUMBER_BRANCH_NAME }}
          else
              git checkout -b ${{ env.CUCUMBER_BRANCH_NAME }}
              git commit -m "Updated Cucumber Feature Files"
              git push --set-upstream origin ${{ env.CUCUMBER_BRANCH_NAME }}
          fi
