name: 'Cucumber to Azure DevOps Test Plans Sync'
author: 'PavanMudigonda'
description: 'A GitHub Action that Synchronizes test cases in Cucumber Feature Files to Azure DevOps Test Plans'

inputs:
  github_token:
    description: 'GitHub API Access Token'
    default: ${{ github.token }}
    required: false
  ado_pat:
    description: 'Azure DevOps PAT'
    required: true
  ado_org_url:
    description: 'ADO Org URL'
    required: true
  area_path:
    description: 'Area Path of ADO'
    required: false
    default: yes    
  project_id:
    description: 'ADO Project ID'
    required: true
  plan_id:
    description: 'ADO Plan ID'
    required: true
  suite_id:
    description: 'ADO Suite ID. If you want to upload all test cases to single test suite'
    required: false
  feature_wise_test_suites:
    description: 'Cucumber Feature as Suite, yes or no'
    required: false
    default: yes
  feature_path:
    description: 'Path of Cucumber Features'
    required: false
    default: yes
outputs:
  json_response:
    description: "response as JSON"

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'check-circle'
  color: 'green'
