
## This is a SAMPLE metadata file for a GitHub Action.  For more info:
##    https://help.github.com/en/articles/metadata-syntax-for-github-actions

name: create-bug
author: PavanMudigondaTR
description: creates bugs in ADO

## Here you describe your *formal* inputs -- those that are
## documented and can be displayed by the marketplace.
## You also use these to identify the *required* inputs.
inputs:

  ado_pat:
    description: 'Azure DevOps PAT'
    required: true
  organization:
    description: 'Organization'
    required: true
  project:
    description: 'Project'
    required: true 
  reason:
    description: 'Reason'
    required: true
    default: ''
  tags:
    description: 'Tag'
    required: true
    default: 'Automation'
  testRunName:
    description: 'Run Name'
    required: false 
  adoRunId:
    description: 'Run ID'
    required: false     
  workItemType:
    description: 'Work Item Type'
    required: true
    default: 'Bug'
  area:
    description: 'Organization'
    required: true
  assignedTo:
    description: 'Project'
    required: true     
  enable_bug_creation:
    description: 'Flag for enabling Automated Bug Creation'
    default: 'true'
    required: false
## Here you describe your *formal* outputs.
outputs:

  first_output:
    description: what does this output provide?

  second_output:
    description: what does this output provide?

branding:
  color: purple
  icon: terminal

## Even though the Action logic may be implemented
## in PWSH, we still need a NodeJS entry point
runs:
  using: node16
  main: _init/index.js
