name: count-action-users

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  count:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2
      with:
        ref: metrics

    - name: Generate user count JSON endpoint
      uses: cicirello/count-action-users@v1
      with:
        action-list: >
          PavanMudigonda/jacoco-reporter
          tr/cicd_gh-actions-cucumber-ado-sync
          tr/cicd_gh-actions-excel-ado-sync
          tr/cicd_gh-actions-notification
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
