name: Create-Bugs

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest  # For a list of available runner types, refer to
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0    
    - name: create bugs for last run failure
      uses: ./create-bugs
      with:
        organization: tr-ihn-sandbox
        ado_pat: ${{ secrets.ADO_PAT }}
        project: Azure-DevOps-Training
        area: 'Release 1'
        # New defect reported
        # Build Failure
        reason: 'Build Failure'
        tags: ${{ github.run_id }}
        runId: 1468
        # bug
        # task
        workItemType: 'task'
        assignedTo: 'Pavan Mudigonda'
