name: test

on:
  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v3

      - name: Cucumber to ADO Sync
        uses: ./
        env:
            PersonalAccessToken: ${{ secrets.ADO_PAT }}
            BaseUrl: https://dev.azure.com/tr-ihn-sandbox
            Project: Azure DevOps Training
            BaseDirectory: features
            TagIdPrefix: ADO-
            Area: Azure DevOps Training
            GherkinSyncToolId: GHAction
            SetThenStepsAsExpected: false