#3
name: cucumber-ado-sync

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**.md' 
    tags-ignore:
      - '**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v3
      - name: Cucumber to ADO Test Cases Sync
        id: ado_sync
        uses: ./
        with:
            artifactory_token: ${{ secrets.artifactory_token }}
            artifactory_user: ${{ secrets.artifactory_user }}        
            test_cases_sync: true
            test_results_sync: false
            ado_pat: ${{ secrets.ADO_PAT }}
            ado_project_url: https://dev.azure.com/tr-ihn-sandbox/Azure-DevOps-Training
            ado_area_path: '\\Release 1'
            ado_iteration_path: '\\Sprint 1'
            cucumber_path: features
            test_suite_id: 9832

      - name: Cucumber to ADO Test Cases Sync
        if: always()
        shell: bash
        run: echo ${{ steps.ado_sync.outputs.ado_test_run_url }}
        
      # - name: Cucumber to ADO Test Results Sync
      #   uses: ./
      #   with:
      #       test_cases_sync: false
      #       test_results_sync: true
      #       ado_pat: ${{ secrets.ADO_PAT }}
      #       ado_project_url: https://dev.azure.com/tr-ihn-sandbox/Azure-DevOps-Training
      #       ado_area_path: '\\Release 1'
      #       ado_iteration_path: '\\Sprint 1'
      #       test_result_file_path: ''
      #       test_result_file_format: ''
      #       test_results_test_suite_id: 
      #       test_results_test_plan_id: 

